# NUMPY

NumPy is, just like SciPy, Scikit-Learn, Pandas, etc. one of the packages that we just can’t miss when you’re learning data science, mainly because this library provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

Numpy arrays are great alternatives to Python Lists. Some of the key advantages of Numpy arrays are that they are fast, easy to work with, and give users the opportunity to perform calculations across entire arrays.

A matrix is a two-dimensional data structure where numbers are arranged into rows and columns.

Python doesn't have a built-in type for matrices. However, we can treat list of a list as a matrix. For example:


A = [[1, 4, 5], 
    [-5, 8, 9]]

### NumPy Array
NumPy is a package for scientific computing which has support for a powerful N-dimensional array object. 

Once NumPy is installed, you can import and use it. 

NumPy provides multidimensional array of numbers (which is actually an object). Let's take an example:

In [10]:
import numpy as np
a = np.array([1, 2, 3])
print(a)               # Output: [1, 2, 3]
print(type(a))         # Output: <class 'numpy.ndarray'>

[1 2 3]
<class 'numpy.ndarray'>


### Matrix Operations

In [11]:
# Addition

import numpy as np
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

[[11  1]
 [ 8  0]]


In [12]:
# Multiplication

import numpy as np
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = a.dot(B)
print(C)

[14 -6]


In [9]:
# Transpose of a Matrix

import numpy as np
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


### Access matrix elements, rows and columns

###### Access matrix elements

In [ ]:
import numpy as np
A = np.array([2, 4, 6, 8, 10])
print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element 

In [14]:
import numpy as np

A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1]) 

A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19


###### Access rows of a Matrix

In [15]:
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 1  4  5 12]
A[2] = [-6  7 11 19]
A[-1] = [-6  7 11 19]


###### Access columns of a Matrix

In [16]:
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)

A[:,0] = [ 1 -5 -6]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


###### Slicing of a Matrix

In [17]:
import numpy as np
letters = np.array([1, 3, 5, 7, 9, 7, 5])

# 3rd to 5th elements
print(letters[2:5])        # Output: [5, 7, 9]

# 1st to 4th elements
print(letters[:-5])        # Output: [1, 3]   

# 6th to last elements
print(letters[5:])         # Output:[7, 5]

# 1st to last elements
print(letters[:])          # Output:[1, 3, 5, 7, 9, 7, 5]

# reversing a list
print(letters[::-1])          # Output:[5, 7, 9, 7, 5, 3, 1]

[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


In [21]:
# slice a matrix

import numpy as np

A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print ("<--------two rows, four columns-------->")
print(A[:2, :4])  # two rows, four columns


print("<--------first row, all columns-------->")
print(A[:1,])  # first row, all columns


print("<--------all rows, second column-------->")
print(A[:,2])  # all rows, second column


print("--------all rows, third to fifth column-------->")
print(A[:, 2:5])  # all rows, third to fifth column


<--------two rows, four columns-------->
[[ 1  4  5 12]
 [-5  8  9  0]]
<--------first row, all columns-------->
[[ 1  4  5 12 14]]
<--------all rows, second column-------->
[ 5  9 11]
--------all rows, third to fifth column-------->
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]


In [5]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)